<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net10.0-android</TargetFrameworks>
    <SupportedOSPlatformVersion Condition=" $(TargetFramework.EndsWith('-android')) ">24</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.19.0.0</Version>
    <Copyright>Copyright © Perfare 2020-2022; Copyright © hozuki 2020</Copyright>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetStudio.PInvoke\AssetStudio.PInvoke.csproj" />
  </ItemGroup>

</Project>
